language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

script:
  - python setup.py build install
  - python setup.py test
  - bash tests/build_example.sh

before_install:
 - apt-get istall -y nodejs npm

notifications:
  emails:
    - aiokada@hgc.jp
  on_success: change
  on_failure: always
