sudo: false

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
      - nodejs
      - npm

script:
  - python setup.py build install
  - coverage run --source=./scripts setup.py test
  - coverage xml
  - coverage report
  - bash tests/build_example.sh
  - cd tests
  - npm i -g npm
  - npm install
  - npm test

before_script:
 - pip install coverage

notifications:
  emails:
    - aiokada@hgc.jp
  on_success: change
  on_failure: always
