sudo: false

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

exclude:
  - python: 2.7
    ENV: NPM_FLG="T"
  - python: 3.3
    ENV: NPM_FLG="F"
  - python: 3.4
    ENV: NPM_FLG="F"
  - python: 3.5
    ENV: NPM_FLG="F"
  - python: 3.6
    ENV: NPM_FLG="F"

addons:
  apt:
    packages:
      - nodejs
      - npm

before_script:
 - pip install coverage
 - wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778-linux.zip
 - unzip sonar-scanner-cli-3.0.3.778-linux.zip
 - export PATH=`pwd`/sonar-scanner-3.0.3.778-linux/bin:$PATH

script:
  - python setup.py build install
  - coverage run --source=./scripts setup.py test
  - if [[ NPM_FLG="T" ]]; then coverage xml; fi
  - if [[ NPM_FLG="T" ]]; then coverage report; fi
  - if [[ NPM_FLG="T" ]]; then bash tests/build_example.sh; fi
  - if [[ NPM_FLG="T" ]]; then cd tests; fi
  - if [[ NPM_FLG="T" ]]; then npm i -g npm; fi
  - if [[ NPM_FLG="T" ]]; then npm install; fi
  - if [[ NPM_FLG="T" ]]; then npm test; fi

after_success:
  - if [[ NPM_FLG="T" ]]; then cd ..; sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=paplot_devel -Dsonar.sources=. -Dsonar.inclusions=paplot,scripts/*.py,scripts/paplot/*.py,scripts/paplot/subcode/*.py,tests/src/js/*.js,tests/src/html/*.js -Dsonar.python.coverage.reportPath=coverage.xml -Dsonar.javascript.lcov.reportPaths=tests/coverage/lcov.info -Dsonar.organization=${SONNAR_KEY} -Dsonar.login=${SONNAR_TOKEN}; fi


notifications:
  emails:
    - aiokada@hgc.jp
  on_success: change
  on_failure: always
